add x button for closing a panel
bmw-software-engineering/lichtblick pull request #90
Opened 2024-07-16 11:36 UTC by Simsalabim1234

**User-Facing Changes**

**Description**
This PR removes the "Remove Panel" button from the dropdown list when clicking the settings button of a panel, and instead adds an x button right next to it. This shall make closing a panel easier.

![Screenshot 2024-07-16 133438](https://github.com/user-attachments/assets/e979d419-7caf-4d71-83f2-39a37f9d0358)

**Checklist**

- [x] The web version was tested and it is running ok
- [x] The desktop version was tested and it is running ok
- [ ] I've updated/created the storybook file(s)
- [ ] The release version was updated on package.json files

2024-07-22 15:32 UTC, aneuwald-ctw requested changes
@Simsalabim1234 could you check the errors regards to the CI Pipeline? It seems that there is some unused variables.

You can try to fix locally and run the command "lint:ci", which will give you the errors before going to CI again :)

2024-07-23 08:51 UTC, markushankh-bmw commented
There is a tradeoff between conveniently closing the panel and accidentally closing it when in fact you wanted to hit one of the other buttons. I would argue that closing the panel of a layout is not a task you have to do very frequently, so I'd rather avoid the accidental closing as it can be cumbersome to reopen a panel, reconfigure it and place it in the right spot. However, an option could be to offer this as a setting for users who might often have the panel-closing step in their workflow.

2024-07-29 14:50 UTC, aneuwald-ctw commented
This PR will not be accepted at this time, because it is not a priority on the project. It can be a good improvement, but it can also impact the UX, as users can close panels by accident. If in the future it become a high priority request, we can reopen this Pull Request.

2024-07-29 14:50 UTC, closed without merging

2024-07-30 06:35 UTC, Simsalabim1234 commented
@aneuwald-ctw  @markushankh-bmw  Yes I understand that having this x-button might be dangerous :) Maybe we can add it in the future as an option, but it's also fine to leave it like it is. Thanks for your feedback!